### ISSUE TITLE
Captura de Turmas do Matrícula Web

### ISSUE THREAD

**Issue by lievertom** [2019-2-arquitetura-desenho/monitoria-crawler#6]
## Descrição
Eu, como ***desenvolvedor***, gostaria de ***recuperar todas as turmas de oferta do Matrícula Web (UnB)*** para ***disponibilizar na aplicação as ofertas de monitoria ao usuário***.

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)
* Todas as turmas da oferta do Matrícula Web devem ser capturadas;

## Tarefas
- [ ] Fazer crawler para recuperar todas as turmas da oferta do Matrícula Web;
- [ ] Turmas devem conter nome, vagas, turno, horário, local e professor principalmente;

**Comment by WelisonR** [comment]
Fechado pelo Pull Request #11.
